-- La tabla "pagos" es creada/gestionada automáticamente por Hibernate (ddl-auto).
-- Los datos semilla se cargan exclusivamente vía DataLoader (CommandLineRunner),
-- por lo que esta migración ya no inserta registros de ejemplo.
