spring.application.name=ms-vehiculos
#Puerto
server.port=8082
#Usuario MySQL
spring.datasource.username=root
#Contraseña
spring.datasource.password=
#JPA
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/prueba1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
